using FMMSRestaurant.Models;
using FMMSRestaurant.ViewModels;

namespace FMMSRestaurant.Pages;

public partial class MainPage : ContentPage
{
    private readonly HomeViewModel _homeViewModel;
    private readonly SettingsViewModel _settingsViewModel;

    // Constructor with Dependency Injection (DI)
    public MainPage(HomeViewModel homeViewModel, SettingsViewModel settingsViewModel)
    {
        InitializeComponent(); // Automatically generated by MAUI
        _homeViewModel = homeViewModel; // Set injected HomeViewModel
        _settingsViewModel = settingsViewModel; // Set injected SettingsViewModel
        BindingContext = _homeViewModel; // Bind to the HomeViewModel
    }

    // Overriding OnAppearing to load async data for the page
    protected override async void OnAppearing()
    {
        base.OnAppearing();
        await _homeViewModel.InitializeAsync(); // Initialize HomeViewModel asynchronously
        await _settingsViewModel.InitializeAsync(); // Initialize SettingsViewModel asynchronously
    }

    private void OnCategorySelected(object sender, MenuCategoryModel category)
    {
        if (category != null)
        {
            _homeViewModel.SelectCategoryCommand.Execute(category); // Execute category selection
        }
    }

    private void OnItemSelected(object sender, MenuItemModel menuItem)
    {
        if (menuItem != null)
        {
            _homeViewModel.AddToCartCommand.Execute(menuItem); // Add item to cart
        }
    }
}
